apiVersion: v1
data:
  mapRoles: |
  - rolearn: arn:aws:iam::300539249420:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "<AUTO_GENERATED_VALUE>"
  name: aws-auth
  namespace: kube-system
  resourceVersion: <AUTO_GENERATED_VALUE>
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: <AUTO_GENERATED_VALUE>
